version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mern_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/devopsdb
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
