# Étape 1 : Utiliser une image Node officielle
FROM node:18

# Étape 2 : Définir le dossier de travail
WORKDIR /app

# Étape 3 : Copier les fichiers du backend
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste du code
COPY . .

# Étape 6 : Exposer le port 5000
EXPOSE 5000

# Étape 7 : Lancer le serveur
CMD ["npm", "run", "dev"]
